services:
  - type: web
    name: tic-tac-toe-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://tic-tac-toe-frontend.onrender.com

  - type: web
    name: tic-tac-toe-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://tic-tac-toe-backend.onrender.com
      - key: REACT_APP_SOCKET_URL
        value: https://tic-tac-toe-backend.onrender.com 